### ISSUE TITLE
not working fully on linux

### ISSUE THREAD

**Issue by valdoonicanlives** [ktgw0316/lightzone-plugin-for-gimp#1]
Hi, first thanks for fixing this to work on linux too.
Edit, left below in case others have a problem but it's not the scripts fault I had not changed the settings in Lightzone, preferences, the save settings need to be "unlimited" and 100% and then it works fine for me.
The paths must be right as lightzone gets called correctly and opens,
the problem is when it saves and I look at the saved layer in gimp it is only part of the picture that is saved.
lightzone 4.1.7-0

**Comment by ktgw0316** [comment]
I've just added the info in README.md. Thank you. :)
